export enum ACTION_TYPE {
  // see applications.ts
  ACTIONS_REQUESTED = 'ACTIONS_REQUESTED',
  ACTIONS_LOADED = 'ACTIONS_LOADED',
  CONTENT_TYPES_REQUESTED = 'CONTENT_TYPES_REQUESTED',
  CONTENT_TYPES_LOADED = 'CONTENT_TYPES_LOADED',
  CLEAR_MESSAGE = 'CLEAR_MESSAGE',
  CLEAR_ALL_MESSAGES = 'CLEAR_ALL_MESSAGES',
  CLOSE_DRAWER = 'CLOSE_DRAWER',
  OPEN_DRAWER = 'OPEN_DRAWER',
  SET_MESSAGE = 'SET_MESSAGE',
  MENU_REQUESTED = 'MENU_REQUESTED',
  MENU_LOADED = 'MENU_LOADED',

  // see constants.ts
  ACTION_EXECUTE = 'ACTION_EXECUTE',
  CONTENT_REQUESTED = 'CONTENT_REQUESTED',
  CONTENT_LOADED = 'CONTENT_LOADED',
  CONTENT_SINGLE_REQUESTED = 'CONTENT_SINGLE_REQUESTED',
  CONTENT_SINGLE_LOADED = 'CONTENT_SINGLE_LOADED',
  CONTENT_ADD_CHANGE = 'CONTENT_ADD_CHANGE',
  CONTENT_EDIT_CHANGE = 'CONTENT_EDIT_CHANGE',
  CONTENT_ADD = 'CONTENT_ADD',
  CONTENT_SAVE = 'CONTENT_SAVE',
  CONTENT_DELETE = 'CONTNENT_DELETE',
  USER_REQUESTED = 'USER_REQUESTED',
  USER_LOADED = 'USER_LOADED',

  LOCATION_CHANGE = 'LOCATION_CHANGE',

  // see helper.ts
  CANCEL_TASK = 'CANCEL_TASK',

  // see roles.ts
  ROLES_REQUESTED = 'ROLES_REQUESTED',
  ROLES_LOADED = 'ROLES_LOADED',

  DBLOG_COLLECTION_LOADED = 'DBLOG_COLLECTION_LOADED',
  DBLOG_FILTER_UPDATED = 'DBLOG_FILTER_UPDATED',

  // see schema.ts
  SCHEMA_REQUESTED = 'SCHEMA_REQUESTED',
  SCHEMA_LOADED = 'SCHEMA_LOADED',
  SCHEMA_BY_ENTITY_ID_REQUESTED = 'SCHEMA_BY_ENTITY_ID_REQUESTED',
  SCHEMA_BY_ENTITY_ID_LOADED = 'SCHEMA_BY_ENTITY_ID_LOADED',
  UI_SCHEMA_REQUESTED = 'UI_SCHEMA_REQUESTED',
  UI_SCHEMA_LOADED = 'UI_SCHEMA_LOADED',

  // see taxonomy.ts
  TAXONOMY_VOCABULARY_LOADED = 'TAXONOMY_VOCABULARY_LOADED',
  TAXONOMY_TERMS_LOADED = 'TAXONOMY_TERMS_LOADED',
}

export default ACTION_TYPE;
